*
* Example program 1 for UT4
* Output a string
* Using UT4 routine
*
	.CR	1802
	.OR	$0000
	.TF	sample1.hex,HEX
*
DELAY1 .EQ $80EF
CONST2 .EQ $2800

INIT:	DIS				..DISABLE INTERRUPTS
	.DB $00
	LDI /WRITE 			..LOAD MAIN PC R5 
	PHI 5
	LDI #WRITE			..U1TH START ADDRESS
	PLO 5
	SEP 5				..CHANGE PC FROM (>> TO S

WRITE:
	LDI /DELAY1
	PHI 12				..INIT DELAY POINTER
	LDI #DELAY1
	PLO 12	 

	LDI /CONST2
	PHI 14				..INIT THE CONSTANT
	LDI #CONST2
	PLO 14				...AND ECHO BIT

	LDI /TEXT
	PHI 6				..PREPARE TEXT POINTER
	LDI #TEXT
	PLO 6

	LDI $81
	PHI 3				..LOAD R3 UITH 819C TO
	LDI $9C
	PLO 3				..DO A TYPE5D FIRST
	SEP 3				..EXECUTE TYPE5D
	.DB $00

OUTPUT:
	LDI $A4
	PLO 3				..PREPARE R3 FOR TYPE
	LDA 6
	PHI 15				..GET BYTE IN RF.1 AND D
	BZ DELAY			..IF IT IS 00 GO TO DELAY
	SEP 3 				..OTHERWISE SEND IT
	BR OUTPUT			..BACK AGAIN

DELAY:
	LDI $FF				..LOAD DELAY CONSTANT
	PHI 7 				..IN R7
LOOP:	DEC 7				..DEC (HIS REGISTER
	GHI 7				..GET R7.1 IN D-REGISTER
	BNZ LOOP			..IE NOT 00 DEC AGAIN
	BR WRITE			..GO TO NEXT CHARACTER	

TEXT:	.DB	$0D,$0A
	.AS	/RCA BRUSSELS/
	.DB	$0D,$0A
	.AS	/STRING OUTPUT/
	.DB	$0D,$0A
	.AS	/USING UT4 ROUTINES/
	.DB	$00			..END OF STRING

	.EN
